name: flutter_cluster_manager_2
description: Simple Flutter clustering library for Google Maps and Apple Maps based on Geohash.
version: 3.2.3
homepage: https://github.com/sampie9999/apple_map_cluster_manager_2
repository: https://github.com/sampie9999/apple_map_cluster_manager_2
issue_tracker: https://github.com/sampie9999/apple_map_cluster_manager_2/issues

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter_platform_interface: ^2.6.0
  apple_maps_flutter: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

topics:
  - google-maps
  - google-maps-flutter
  - apple-maps
  - apple-maps-flutter
  - map
  - cluster

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
